using System.Text;
using CsWasm.Diagnostics;
using CsWasm.Frontend.Cil.Ssa;

namespace CsWasm.Backend.MoonBit.Emitter;

/// <summary>
/// Walks the SSA of one assembly and writes MoonBit source for it: the whole of the first
/// backend, with <c>emit_type</c> here and <c>emit_function</c> and <c>emit_instruction</c>
/// beside it (docs/architecture.md section 9.1).
/// </summary>
/// <remarks>
/// There is no backend interface and no visitor hierarchy. Section 9.1 says the second backend
/// is what shows where the seam belongs, and inventing one now would fix it in the wrong place.
/// <para>
/// The generated text is an output format, not a representation anything else reads back
/// (section 4.2): every piece of MoonBit syntax cswasm knows is in this directory, and the
/// passes in front of it carry only .NET semantics.
/// </para>
/// <para>
/// The output is decided by the model alone - types and methods in metadata order, blocks in
/// IL offset order, identifiers from .NET identity - so two runs over the same assembly agree
/// byte for byte and no path, timestamp or hash iteration order reaches it.
/// </para>
/// </remarks>
public static class MoonBitEmitter
{
    private const char LineFeed = '\n';

    private const string Header =
        "// Generated by cswasm. This is an output format, not an intermediate representation.\n"
        + "// Identifiers come from .NET identity alone, never from the file the assembly was read from.\n"
        + "// This step inserts no implicit exception checks; see docs/reports/step1.md and CSW1005.\n";

    /// <summary>
    /// Writes <paramref name="assembly"/> into <paramref name="module"/> and returns the
    /// diagnostics of the run. <paramref name="module"/> is null when any of them is an error:
    /// a file describing part of an assembly would read as if it described all of it
    /// (docs/diagnostics.md rule 1).
    /// </summary>
    public static IReadOnlyList<Diagnostic> Emit(SpikeSsaAssembly assembly, out MoonBitModule? module)
    {
        ArgumentNullException.ThrowIfNull(assembly);

        var diagnostics = new List<Diagnostic>();
        var text = new StringBuilder(Header);
        var exports = new List<string>();

        foreach (var type in assembly.Types)
        {
            text.Append(LineFeed);
            text.Append(EmitType(type, diagnostics));

            foreach (var method in type.Methods)
            {
                var warning = ImplicitExceptionChecks.For(type.FullName, method);
                if (warning is not null)
                {
                    diagnostics.Add(warning);
                }

                var function = new MoonBitFunctionEmitter(type.FullName, method, diagnostics).Emit();
                if (function is null)
                {
                    continue;
                }

                text.Append(LineFeed);
                text.Append(function.Text);

                if (function.IsExported)
                {
                    exports.Add(function.Name);
                }
            }
        }

        module = diagnostics.Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            ? null
            : new MoonBitModule(text.ToString(), exports);

        return diagnostics;
    }

    /// <summary>
    /// <c>emit_type</c>: a C# class becomes a MoonBit struct whose fields are mutable, which
    /// is the mapping issue #16 fixes. The C# field names are carried over so that a reader
    /// can line the struct up with the class it came from.
    /// </summary>
    private static string EmitType(SpikeSsaTypeDefinition type, List<Diagnostic> diagnostics)
    {
        var text = new StringBuilder();
        text.Append("// ").Append(type.FullName).Append(LineFeed);
        text.Append("struct ").Append(MoonBitNames.OfType(type.FullName)).Append(" {").Append(LineFeed);

        foreach (var field in type.Fields)
        {
            var fieldType = field.Type is null ? null : MoonBitTypeNames.Of(field.Type);

            if (fieldType is null)
            {
                diagnostics.Add(new Diagnostic(
                    DiagnosticCode.BackendCannotLower,
                    DiagnosticSeverity.Error,
                    $"the field '{type.FullName}::{field.Name}' has a type this step cannot write down in "
                    + "MoonBit.",
                    type.FullName + "::" + field.Name,
                    "Issue #16 maps the proof-of-concept subset; later steps widen it."));
                continue;
            }

            text.Append("  mut ")
                .Append(MoonBitNames.OfField(type.FullName, field.Name))
                .Append(" : ")
                .Append(fieldType)
                .Append(LineFeed);
        }

        text.Append('}').Append(LineFeed);
        return text.ToString();
    }
}
