namespace CsWasm.Frontend.Cil;

/// <summary>
/// The operand encoding of an opcode, using the ECMA-335 names.
/// </summary>
internal enum IlOperandKind
{
    InlineNone,
    ShortInlineI,
    InlineI,
    InlineI8,
    ShortInlineR,
    InlineR,
    ShortInlineVar,
    InlineVar,
    ShortInlineBrTarget,
    InlineBrTarget,
    InlineSwitch,
    InlineField,
    InlineMethod,
    InlineType,
    InlineTok,
    InlineString,
    InlineSig,
}

internal sealed record IlOpCodeInfo(string Name, IlOperandKind Operand);

/// <summary>
/// The full ECMA-335 opcode table, not just the subset cswasm supports. Reporting every
/// unsupported opcode in one run (CSW1001) means the decoder has to know how long each
/// instruction is, including the ones it will refuse.
/// </summary>
internal static class IlOpCodes
{
    /// <summary>The escape byte that introduces a two-byte opcode.</summary>
    public const byte Prefix = 0xfe;

    private static readonly Dictionary<byte, IlOpCodeInfo> OneByte = new()
    {
        [0x00] = new("nop", IlOperandKind.InlineNone),
        [0x01] = new("break", IlOperandKind.InlineNone),
        [0x02] = new("ldarg.0", IlOperandKind.InlineNone),
        [0x03] = new("ldarg.1", IlOperandKind.InlineNone),
        [0x04] = new("ldarg.2", IlOperandKind.InlineNone),
        [0x05] = new("ldarg.3", IlOperandKind.InlineNone),
        [0x06] = new("ldloc.0", IlOperandKind.InlineNone),
        [0x07] = new("ldloc.1", IlOperandKind.InlineNone),
        [0x08] = new("ldloc.2", IlOperandKind.InlineNone),
        [0x09] = new("ldloc.3", IlOperandKind.InlineNone),
        [0x0a] = new("stloc.0", IlOperandKind.InlineNone),
        [0x0b] = new("stloc.1", IlOperandKind.InlineNone),
        [0x0c] = new("stloc.2", IlOperandKind.InlineNone),
        [0x0d] = new("stloc.3", IlOperandKind.InlineNone),
        [0x0e] = new("ldarg.s", IlOperandKind.ShortInlineVar),
        [0x0f] = new("ldarga.s", IlOperandKind.ShortInlineVar),
        [0x10] = new("starg.s", IlOperandKind.ShortInlineVar),
        [0x11] = new("ldloc.s", IlOperandKind.ShortInlineVar),
        [0x12] = new("ldloca.s", IlOperandKind.ShortInlineVar),
        [0x13] = new("stloc.s", IlOperandKind.ShortInlineVar),
        [0x14] = new("ldnull", IlOperandKind.InlineNone),
        [0x15] = new("ldc.i4.m1", IlOperandKind.InlineNone),
        [0x16] = new("ldc.i4.0", IlOperandKind.InlineNone),
        [0x17] = new("ldc.i4.1", IlOperandKind.InlineNone),
        [0x18] = new("ldc.i4.2", IlOperandKind.InlineNone),
        [0x19] = new("ldc.i4.3", IlOperandKind.InlineNone),
        [0x1a] = new("ldc.i4.4", IlOperandKind.InlineNone),
        [0x1b] = new("ldc.i4.5", IlOperandKind.InlineNone),
        [0x1c] = new("ldc.i4.6", IlOperandKind.InlineNone),
        [0x1d] = new("ldc.i4.7", IlOperandKind.InlineNone),
        [0x1e] = new("ldc.i4.8", IlOperandKind.InlineNone),
        [0x1f] = new("ldc.i4.s", IlOperandKind.ShortInlineI),
        [0x20] = new("ldc.i4", IlOperandKind.InlineI),
        [0x21] = new("ldc.i8", IlOperandKind.InlineI8),
        [0x22] = new("ldc.r4", IlOperandKind.ShortInlineR),
        [0x23] = new("ldc.r8", IlOperandKind.InlineR),
        [0x25] = new("dup", IlOperandKind.InlineNone),
        [0x26] = new("pop", IlOperandKind.InlineNone),
        [0x27] = new("jmp", IlOperandKind.InlineMethod),
        [0x28] = new("call", IlOperandKind.InlineMethod),
        [0x29] = new("calli", IlOperandKind.InlineSig),
        [0x2a] = new("ret", IlOperandKind.InlineNone),
        [0x2b] = new("br.s", IlOperandKind.ShortInlineBrTarget),
        [0x2c] = new("brfalse.s", IlOperandKind.ShortInlineBrTarget),
        [0x2d] = new("brtrue.s", IlOperandKind.ShortInlineBrTarget),
        [0x2e] = new("beq.s", IlOperandKind.ShortInlineBrTarget),
        [0x2f] = new("bge.s", IlOperandKind.ShortInlineBrTarget),
        [0x30] = new("bgt.s", IlOperandKind.ShortInlineBrTarget),
        [0x31] = new("ble.s", IlOperandKind.ShortInlineBrTarget),
        [0x32] = new("blt.s", IlOperandKind.ShortInlineBrTarget),
        [0x33] = new("bne.un.s", IlOperandKind.ShortInlineBrTarget),
        [0x34] = new("bge.un.s", IlOperandKind.ShortInlineBrTarget),
        [0x35] = new("bgt.un.s", IlOperandKind.ShortInlineBrTarget),
        [0x36] = new("ble.un.s", IlOperandKind.ShortInlineBrTarget),
        [0x37] = new("blt.un.s", IlOperandKind.ShortInlineBrTarget),
        [0x38] = new("br", IlOperandKind.InlineBrTarget),
        [0x39] = new("brfalse", IlOperandKind.InlineBrTarget),
        [0x3a] = new("brtrue", IlOperandKind.InlineBrTarget),
        [0x3b] = new("beq", IlOperandKind.InlineBrTarget),
        [0x3c] = new("bge", IlOperandKind.InlineBrTarget),
        [0x3d] = new("bgt", IlOperandKind.InlineBrTarget),
        [0x3e] = new("ble", IlOperandKind.InlineBrTarget),
        [0x3f] = new("blt", IlOperandKind.InlineBrTarget),
        [0x40] = new("bne.un", IlOperandKind.InlineBrTarget),
        [0x41] = new("bge.un", IlOperandKind.InlineBrTarget),
        [0x42] = new("bgt.un", IlOperandKind.InlineBrTarget),
        [0x43] = new("ble.un", IlOperandKind.InlineBrTarget),
        [0x44] = new("blt.un", IlOperandKind.InlineBrTarget),
        [0x45] = new("switch", IlOperandKind.InlineSwitch),
        [0x46] = new("ldind.i1", IlOperandKind.InlineNone),
        [0x47] = new("ldind.u1", IlOperandKind.InlineNone),
        [0x48] = new("ldind.i2", IlOperandKind.InlineNone),
        [0x49] = new("ldind.u2", IlOperandKind.InlineNone),
        [0x4a] = new("ldind.i4", IlOperandKind.InlineNone),
        [0x4b] = new("ldind.u4", IlOperandKind.InlineNone),
        [0x4c] = new("ldind.i8", IlOperandKind.InlineNone),
        [0x4d] = new("ldind.i", IlOperandKind.InlineNone),
        [0x4e] = new("ldind.r4", IlOperandKind.InlineNone),
        [0x4f] = new("ldind.r8", IlOperandKind.InlineNone),
        [0x50] = new("ldind.ref", IlOperandKind.InlineNone),
        [0x51] = new("stind.ref", IlOperandKind.InlineNone),
        [0x52] = new("stind.i1", IlOperandKind.InlineNone),
        [0x53] = new("stind.i2", IlOperandKind.InlineNone),
        [0x54] = new("stind.i4", IlOperandKind.InlineNone),
        [0x55] = new("stind.i8", IlOperandKind.InlineNone),
        [0x56] = new("stind.r4", IlOperandKind.InlineNone),
        [0x57] = new("stind.r8", IlOperandKind.InlineNone),
        [0x58] = new("add", IlOperandKind.InlineNone),
        [0x59] = new("sub", IlOperandKind.InlineNone),
        [0x5a] = new("mul", IlOperandKind.InlineNone),
        [0x5b] = new("div", IlOperandKind.InlineNone),
        [0x5c] = new("div.un", IlOperandKind.InlineNone),
        [0x5d] = new("rem", IlOperandKind.InlineNone),
        [0x5e] = new("rem.un", IlOperandKind.InlineNone),
        [0x5f] = new("and", IlOperandKind.InlineNone),
        [0x60] = new("or", IlOperandKind.InlineNone),
        [0x61] = new("xor", IlOperandKind.InlineNone),
        [0x62] = new("shl", IlOperandKind.InlineNone),
        [0x63] = new("shr", IlOperandKind.InlineNone),
        [0x64] = new("shr.un", IlOperandKind.InlineNone),
        [0x65] = new("neg", IlOperandKind.InlineNone),
        [0x66] = new("not", IlOperandKind.InlineNone),
        [0x67] = new("conv.i1", IlOperandKind.InlineNone),
        [0x68] = new("conv.i2", IlOperandKind.InlineNone),
        [0x69] = new("conv.i4", IlOperandKind.InlineNone),
        [0x6a] = new("conv.i8", IlOperandKind.InlineNone),
        [0x6b] = new("conv.r4", IlOperandKind.InlineNone),
        [0x6c] = new("conv.r8", IlOperandKind.InlineNone),
        [0x6d] = new("conv.u4", IlOperandKind.InlineNone),
        [0x6e] = new("conv.u8", IlOperandKind.InlineNone),
        [0x6f] = new("callvirt", IlOperandKind.InlineMethod),
        [0x70] = new("cpobj", IlOperandKind.InlineType),
        [0x71] = new("ldobj", IlOperandKind.InlineType),
        [0x72] = new("ldstr", IlOperandKind.InlineString),
        [0x73] = new("newobj", IlOperandKind.InlineMethod),
        [0x74] = new("castclass", IlOperandKind.InlineType),
        [0x75] = new("isinst", IlOperandKind.InlineType),
        [0x76] = new("conv.r.un", IlOperandKind.InlineNone),
        [0x79] = new("unbox", IlOperandKind.InlineType),
        [0x7a] = new("throw", IlOperandKind.InlineNone),
        [0x7b] = new("ldfld", IlOperandKind.InlineField),
        [0x7c] = new("ldflda", IlOperandKind.InlineField),
        [0x7d] = new("stfld", IlOperandKind.InlineField),
        [0x7e] = new("ldsfld", IlOperandKind.InlineField),
        [0x7f] = new("ldsflda", IlOperandKind.InlineField),
        [0x80] = new("stsfld", IlOperandKind.InlineField),
        [0x81] = new("stobj", IlOperandKind.InlineType),
        [0x82] = new("conv.ovf.i1.un", IlOperandKind.InlineNone),
        [0x83] = new("conv.ovf.i2.un", IlOperandKind.InlineNone),
        [0x84] = new("conv.ovf.i4.un", IlOperandKind.InlineNone),
        [0x85] = new("conv.ovf.i8.un", IlOperandKind.InlineNone),
        [0x86] = new("conv.ovf.u1.un", IlOperandKind.InlineNone),
        [0x87] = new("conv.ovf.u2.un", IlOperandKind.InlineNone),
        [0x88] = new("conv.ovf.u4.un", IlOperandKind.InlineNone),
        [0x89] = new("conv.ovf.u8.un", IlOperandKind.InlineNone),
        [0x8a] = new("conv.ovf.i.un", IlOperandKind.InlineNone),
        [0x8b] = new("conv.ovf.u.un", IlOperandKind.InlineNone),
        [0x8c] = new("box", IlOperandKind.InlineType),
        [0x8d] = new("newarr", IlOperandKind.InlineType),
        [0x8e] = new("ldlen", IlOperandKind.InlineNone),
        [0x8f] = new("ldelema", IlOperandKind.InlineType),
        [0x90] = new("ldelem.i1", IlOperandKind.InlineNone),
        [0x91] = new("ldelem.u1", IlOperandKind.InlineNone),
        [0x92] = new("ldelem.i2", IlOperandKind.InlineNone),
        [0x93] = new("ldelem.u2", IlOperandKind.InlineNone),
        [0x94] = new("ldelem.i4", IlOperandKind.InlineNone),
        [0x95] = new("ldelem.u4", IlOperandKind.InlineNone),
        [0x96] = new("ldelem.i8", IlOperandKind.InlineNone),
        [0x97] = new("ldelem.i", IlOperandKind.InlineNone),
        [0x98] = new("ldelem.r4", IlOperandKind.InlineNone),
        [0x99] = new("ldelem.r8", IlOperandKind.InlineNone),
        [0x9a] = new("ldelem.ref", IlOperandKind.InlineNone),
        [0x9b] = new("stelem.i", IlOperandKind.InlineNone),
        [0x9c] = new("stelem.i1", IlOperandKind.InlineNone),
        [0x9d] = new("stelem.i2", IlOperandKind.InlineNone),
        [0x9e] = new("stelem.i4", IlOperandKind.InlineNone),
        [0x9f] = new("stelem.i8", IlOperandKind.InlineNone),
        [0xa0] = new("stelem.r4", IlOperandKind.InlineNone),
        [0xa1] = new("stelem.r8", IlOperandKind.InlineNone),
        [0xa2] = new("stelem.ref", IlOperandKind.InlineNone),
        [0xa3] = new("ldelem", IlOperandKind.InlineType),
        [0xa4] = new("stelem", IlOperandKind.InlineType),
        [0xa5] = new("unbox.any", IlOperandKind.InlineType),
        [0xb3] = new("conv.ovf.i1", IlOperandKind.InlineNone),
        [0xb4] = new("conv.ovf.u1", IlOperandKind.InlineNone),
        [0xb5] = new("conv.ovf.i2", IlOperandKind.InlineNone),
        [0xb6] = new("conv.ovf.u2", IlOperandKind.InlineNone),
        [0xb7] = new("conv.ovf.i4", IlOperandKind.InlineNone),
        [0xb8] = new("conv.ovf.u4", IlOperandKind.InlineNone),
        [0xb9] = new("conv.ovf.i8", IlOperandKind.InlineNone),
        [0xba] = new("conv.ovf.u8", IlOperandKind.InlineNone),
        [0xc2] = new("refanyval", IlOperandKind.InlineType),
        [0xc3] = new("ckfinite", IlOperandKind.InlineNone),
        [0xc6] = new("mkrefany", IlOperandKind.InlineType),
        [0xd0] = new("ldtoken", IlOperandKind.InlineTok),
        [0xd1] = new("conv.u2", IlOperandKind.InlineNone),
        [0xd2] = new("conv.u1", IlOperandKind.InlineNone),
        [0xd3] = new("conv.i", IlOperandKind.InlineNone),
        [0xd4] = new("conv.ovf.i", IlOperandKind.InlineNone),
        [0xd5] = new("conv.ovf.u", IlOperandKind.InlineNone),
        [0xd6] = new("add.ovf", IlOperandKind.InlineNone),
        [0xd7] = new("add.ovf.un", IlOperandKind.InlineNone),
        [0xd8] = new("mul.ovf", IlOperandKind.InlineNone),
        [0xd9] = new("mul.ovf.un", IlOperandKind.InlineNone),
        [0xda] = new("sub.ovf", IlOperandKind.InlineNone),
        [0xdb] = new("sub.ovf.un", IlOperandKind.InlineNone),
        [0xdc] = new("endfinally", IlOperandKind.InlineNone),
        [0xdd] = new("leave", IlOperandKind.InlineBrTarget),
        [0xde] = new("leave.s", IlOperandKind.ShortInlineBrTarget),
        [0xdf] = new("stind.i", IlOperandKind.InlineNone),
        [0xe0] = new("conv.u", IlOperandKind.InlineNone),
    };

    private static readonly Dictionary<byte, IlOpCodeInfo> TwoByte = new()
    {
        [0x00] = new("arglist", IlOperandKind.InlineNone),
        [0x01] = new("ceq", IlOperandKind.InlineNone),
        [0x02] = new("cgt", IlOperandKind.InlineNone),
        [0x03] = new("cgt.un", IlOperandKind.InlineNone),
        [0x04] = new("clt", IlOperandKind.InlineNone),
        [0x05] = new("clt.un", IlOperandKind.InlineNone),
        [0x06] = new("ldftn", IlOperandKind.InlineMethod),
        [0x07] = new("ldvirtftn", IlOperandKind.InlineMethod),
        [0x09] = new("ldarg", IlOperandKind.InlineVar),
        [0x0a] = new("ldarga", IlOperandKind.InlineVar),
        [0x0b] = new("starg", IlOperandKind.InlineVar),
        [0x0c] = new("ldloc", IlOperandKind.InlineVar),
        [0x0d] = new("ldloca", IlOperandKind.InlineVar),
        [0x0e] = new("stloc", IlOperandKind.InlineVar),
        [0x0f] = new("localloc", IlOperandKind.InlineNone),
        [0x11] = new("endfilter", IlOperandKind.InlineNone),
        [0x12] = new("unaligned.", IlOperandKind.ShortInlineI),
        [0x13] = new("volatile.", IlOperandKind.InlineNone),
        [0x14] = new("tail.", IlOperandKind.InlineNone),
        [0x15] = new("initobj", IlOperandKind.InlineType),
        [0x16] = new("constrained.", IlOperandKind.InlineType),
        [0x17] = new("cpblk", IlOperandKind.InlineNone),
        [0x18] = new("initblk", IlOperandKind.InlineNone),
        [0x1a] = new("rethrow", IlOperandKind.InlineNone),
        [0x1c] = new("sizeof", IlOperandKind.InlineType),
        [0x1d] = new("refanytype", IlOperandKind.InlineNone),
        [0x1e] = new("readonly.", IlOperandKind.InlineNone),
    };

    /// <summary>Returns null for a byte this table does not define.</summary>
    public static IlOpCodeInfo? Lookup(byte value) =>
        OneByte.TryGetValue(value, out var info) ? info : null;

    /// <summary>Returns null for a <c>0xfe</c>-prefixed byte this table does not define.</summary>
    public static IlOpCodeInfo? LookupPrefixed(byte value) =>
        TwoByte.TryGetValue(value, out var info) ? info : null;

    /// <summary>
    /// The number of operand bytes that follow the opcode, excluding the jump table of a
    /// switch, whose length depends on the case count that is read first.
    /// </summary>
    public static int FixedOperandSize(IlOperandKind kind) => kind switch
    {
        IlOperandKind.InlineNone => 0,
        IlOperandKind.ShortInlineI or IlOperandKind.ShortInlineVar or IlOperandKind.ShortInlineBrTarget => 1,
        IlOperandKind.InlineVar => 2,
        IlOperandKind.InlineI8 or IlOperandKind.InlineR => 8,
        _ => 4,
    };
}
